### ISSUE TITLE
매니저 지원 폼 페이지

### ISSUE THREAD

**Issue by pyozz** [Final-DAMDA/FE_DAMDA#32]
## Description

매니저 지원을 위해 작성하는 페이지

## Todo List

- [ ] 페이지 레이아웃
- [ ] 헤더의 프로필, 무료견적 버튼 미노출

- [ ] 이름, 연락처
  - [ ] 이름 유효성 검사
  - [ ] 연락처 유효성 검사
  - [ ] 연락처 자동 하이픈
- [ ] 활동 가능 요일
- [ ] 활동 가능 지역
  - [ ] 선택한 region에 따른 district 리스트 렌더링 
  - [ ] 선택 지역 태그
  - [ ] 외부 영역 클릭시 닫히도록
- [ ] 자격증 정보
  - [ ] 선택한 정보로 텍스트 변경
  - [ ] 기타 선택시 자격증 입력 input 노출
- [ ] 현장 경험
- [ ] 본업 유무
  - [ ] 본업 있을 시 본업 입력 input 노출
- [ ] 자차 운전 가능 여부
- [ ] 정리 가이드 동의

- [ ] 다음 질문으로 dissolve되어 나타나는 방식
- [ ] 입력에 따른 지원 버튼 활성화
- [ ] 데이터 서버 전송 코드 작성
- [ ] 뒤로가기 팝업
- [ ] 작성 중에 뒤로가기 시 작성된 내용은 저장
- [ ] 지원하기 버튼 클릭시 작성 내용 확인 모달
- [ ] 지원 완료 모달
