### ISSUE TITLE
옷장 관리 페이지

### ISSUE THREAD

**Issue by Nevacat** [Final-DAMDA/FE_DAMDA#43]
## Description
옷장 관리 페이지 제작

## Todo List

- [x] 옷장 정리 방법 캐러셀 구현
- [x] 옷장 정리 장점 탭 구현
- [x] 전문가 설명 팝업 구현
- [ ] 후기 캐러셀 구현
- [x] 서비스 통계 캐러셀 구현
