### ISSUE TITLE
Header/Footer 작업

### ISSUE THREAD

**Issue by tmdgp0212** [Final-DAMDA/FE_DAMDA#5]
## Description

모든 페이지에 걸쳐 보여지는 헤더와 푸터 생성

## Todo List

- [x] 헤더 레이아웃 완성
- [x] 헤더 무료견적 버튼 기능 완성
- [x] 헤더 로그인 버튼 기능 완성
- [x] 헤더 햄버거메뉴 기능 완성
- [x] 푸터 레이아웃 완성
